name: Build Develop Image

on:
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build qemu dependencies for cross-platform build
      run: sudo apt-get install qemu-user-static

    - name: Prepare cross-platform build
      run: docker buildx create --name aeneabot --platform linux/amd64,linux/arm64,linux/arm/v7

    - uses: actions/checkout@v3    
    - name: Build aeneabot project
      run: docker buildx use aeneabot &&
           docker buildx inspect --bootstrap &&
           docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t elautoestopista/aeneabot:$(date +%s) -t elautoestopista/aeneabot:develop . # --push .
